# Generated by Django 4.1.3 on 2022-11-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('music', models.CharField(blank=True, max_length=100)),
                ('food', models.CharField(blank=True, max_length=100)),
                ('drink', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
    ]
