# Generated by Django 4.1.3 on 2022-11-30 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_preference',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
