# Generated by Django 4.1.3 on 2022-11-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_user_preference_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Preference',
        ),
    ]
