# Generated by Django 4.1.3 on 2022-11-30 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_preferences', '0003_delete_user_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('music', models.CharField(blank=True, max_length=100)),
                ('food', models.CharField(blank=True, max_length=100)),
                ('drink', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
    ]
