# Generated by Django 4.1.3 on 2022-12-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_preferences', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_preference',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='user_preference',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_preference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
